In [16]:
import numpy as np
import pandas as pd

In [17]:
atletas = pd.read_csv('../BD/Tablas/atletas.csv')
resultados = pd.read_csv('../BD/Tablas/resultados.csv')
pruebas = pd.read_csv('../BD/Tablas/pruebas.csv')
campeonatos = pd.read_csv('../BD/Tablas/campeonatos.csv')
eventos = pd.read_csv('../BD/Tablas/eventos.csv')

C:\Users\juanj\AppData\Local\Temp\ipykernel_23200\2740464744.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  resultados = pd.read_csv('../BD/Tablas/resultados.csv')

In [19]:
resultados[resultados['id_prueba'] == 51943].sort_values(by='puntos', ascending=False).head(20)

,id_prueba,id_atleta,posicion,atleta,club,pista,resultado,serie,viento,resultado_formateado,puntos
491519,51943,5099.0,1.0,José Clemente Chávez Zurita,Universidad de los Andes,NaN,4:05.54,2.0,NaN,245.54,790.0
491523,51943,9523.0,2.0,Fernando Fritz Berríos,Universidad de Chile,NaN,4:07.68,1.0,NaN,247.68,766.0
491525,51943,40258.0,3.0,Alvaro Sepulveda Umaña,Pontificia Universidad Católica de Chile,NaN,4:08.56,2.0,NaN,248.56,756.0
491526,51943,14882.0,4.0,Cristobal Andres Cabrera Sanchez,Universidad Andrés Bello,NaN,4:13.53,2.0,NaN,253.53,702.0
491536,51943,27505.0,5.0,Vicente Agustin Cea Sepulveda,Universidad de Chile,NaN,4:17.00,1.0,NaN,257.00,666.0
491528,51943,5934.0,6.0,Renato Contreras Salazar,Universidad de Chile,NaN,4:27.53,1.0,NaN,267.53,561.0
491533,51943,19920.0,7.0,David Esteban León Quiñones,Universidad de Santiago,NaN,4:28.86,1.0,NaN,268.86,548.0
491532,51943,4926.0,8.0,Sebastián Novoa Cáceres,Pontificia Universidad Católica de Chile,NaN,4:29.03,1.0,NaN,269.03,546.0
491524,51943,26490.0,9.0,Patricio Enrique Cáceres Sánchez,Universidad Tecnológica Metropolitana,NaN,4:44.19,1.0,NaN,284.19,413.0
491534,51943,25398.0,10.0,Rodrigo Araya Herrera,Universidad de Santiago,NaN,4:45.47,1.0,NaN,285.47,402.0
491531,51943,69060.0,11.0,Matías Alfredo Valdes Araya,Universidad de Santiago,NaN,4:52.91,2.0,NaN,292.91,344.0
491518,51943,40477.0,12.0,Vincenzo Paolo Candiani Hernando,Universidad Andrés Bello,NaN,4:56.28,2.0,NaN,296.28,320.0
491529,51943,2724.0,13.0,Tomas William Toledo Rubilar,Universidad Tecnológica Metropolitana,NaN,5:02.46,2.0,NaN,302.46,277.0
491527,51943,80385.0,14.0,Franco Estefano Lobos Silva,Universidad Metropolitana de Ciencias de la Ed...,NaN,5:14.03,2.0,NaN,314.03,204.0
491520,51943,77306.0,15.0,Mario Paulo Ormazábal Otárola,Universidad Diego Portales,NaN,6:26.37,2.0,NaN,386.37,0.0
491521,51943,80562.0,NaN,Ignacio Hidalgo Severino,Universidad Metropolitana de Ciencias de la Ed...,NaN,DNS,2.0,NaN,NaN,NaN
491522,51943,54919.0,NaN,Lucas Martinez Ramos,Universidad Metropolitana de Ciencias de la Ed...,NaN,DNS,2.0,NaN,NaN,NaN
491530,51943,27548.0,NaN,José Raimundo Dossow Jara,Pontificia Universidad Católica de Chile,NaN,DNS,1.0,NaN,NaN,NaN
491535,51943,63049.0,NaN,Benjamín Alejandro Farias Nuñez,Universidad Mayor,NaN,DNS,1.0,NaN,NaN,NaN
491537,51943,7390.0,NaN,Jose Manuel Silva Ojeda,Universidad Diego Portales,NaN,DNS,1.0,NaN,NaN,NaN

In [14]:
# Ranking 1500 Metros Planos Hombres 2026
ranking_1500m_hombres_2026 = resultados.merge(pruebas, on='id_prueba')
ranking_1500m_hombres_2026 = ranking_1500m_hombres_2026[(ranking_1500m_hombres_2026['nombre'] == '1.500 Metros Planos') & (ranking_1500m_hombres_2026['genero'] == 'Hombres') & (ranking_1500m_hombres_2026['fecha'] >= '2026-01-01') & (ranking_1500m_hombres_2026['fecha'] <= '2026-12-31')]
ranking_1500m_hombres_2026 = ranking_1500m_hombres_2026.sort_values(by='puntos', ascending=False).reset_index(drop=True)
ranking_1500m_hombres_2026 = ranking_1500m_hombres_2026.drop_duplicates(subset=['id_atleta'], keep='first')
ranking_1500m_hombres_2026.head(60)

,id_prueba,id_atleta,posicion,atleta,club,pista,resultado,serie,viento,resultado_formateado,puntos,nombre,fecha,hora,genero,categorias,prueba_padre,timestamp,id_campeonato,id_evento
0,49779,36723.0,1.0,Guilherme Kurtz Kurtz,Brasil,NaN,3:41.41,1.0,NaN,221.41,1088.0,1.500 Metros Planos,2026-04-19,12:45:00,Hombres,GrandPrix,NaN,2026-06-05 00:00:00,1509.0,19
1,49779,6162.0,2.0,Brayan Antonio Jara Jara,Atlético Los Ángeles,NaN,3:44.54,1.0,NaN,224.54,1046.0,1.500 Metros Planos,2026-04-19,12:45:00,Hombres,GrandPrix,NaN,2026-06-05 00:00:00,1509.0,19
2,49779,1842.0,3.0,Lucas Alberto Jara Gaggero,Atlético Francés,NaN,3:45.69,1.0,NaN,225.69,1031.0,1.500 Metros Planos,2026-04-19,12:45:00,Hombres,GrandPrix,NaN,2026-06-05 00:00:00,1509.0,19
3,49779,43425.0,4.0,Gonzalo Gervasini,Uruguay,NaN,3:45.90,1.0,NaN,225.90,1029.0,1.500 Metros Planos,2026-04-19,12:45:00,Hombres,GrandPrix,NaN,2026-06-05 00:00:00,1509.0,19
4,49779,2641.0,5.0,Esteban Gonzalez Sanchez,Atlético Francés,NaN,3:46.51,1.0,NaN,226.51,1021.0,1.500 Metros Planos,2026-04-19,12:45:00,Hombres,GrandPrix,NaN,2026-06-05 00:00:00,1509.0,19
8,49779,24889.0,6.0,Juan Manuel Quijada Bustos,Atlético Yungay,NaN,3:48.85,1.0,NaN,228.85,991.0,1.500 Metros Planos,2026-04-19,12:45:00,Hombres,GrandPrix,NaN,2026-06-05 00:00:00,1509.0,19
10,48256,8055.0,1.0,Carlos Martín Diaz Del Rio,Atlético Santiago,NaN,3:49.64,1.0,NaN,229.64,981.0,1.500 Metros Planos,2026-04-11,12:20:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1503.0,19
13,46672,23328.0,3.0,Alfredo Iván Toledo Salas,Atlético Los Ángeles,NaN,3:50.30,1.0,NaN,230.30,973.0,1.500 Metros Planos,2026-03-07,21:00:00,Hombres,TodoCompetidor,NaN,2026-06-05 00:00:00,1510.0,19
15,46672,27558.0,4.0,Rubén Gerardo Palma Fontealva,Team Rubén,NaN,3:51.78,1.0,NaN,231.78,954.0,1.500 Metros Planos,2026-03-07,21:00:00,Hombres,TodoCompetidor,NaN,2026-06-05 00:00:00,1510.0,19
19,49779,48904.0,7.0,Ericky Manoel Dos Santos Haas,Paraguay,NaN,3:52.17,1.0,NaN,232.17,949.0,1.500 Metros Planos,2026-04-19,12:45:00,Hombres,GrandPrix,NaN,2026-06-05 00:00:00,1509.0,19
20,50305,12402.0,2.0,Sebastian Ignacio Dossow Jara,Atlético Quilamapu,NaN,3:52.39,1.0,NaN,232.39,946.0,1.500 Metros Planos,2026-05-16,17:10:00,Hombres,U23,NaN,2026-06-05 00:00:00,1504.0,19
21,49779,23833.0,8.0,Gaston Gonzalez Mayo,Deportivo Alemán - Valparaiso,NaN,3:52.61,1.0,NaN,232.61,944.0,1.500 Metros Planos,2026-04-19,12:45:00,Hombres,GrandPrix,NaN,2026-06-05 00:00:00,1509.0,19
23,49779,19572.0,9.0,Ronald Mamani Ayca,Ejercito de Chile,NaN,3:52.97,1.0,NaN,232.97,939.0,1.500 Metros Planos,2026-04-19,12:45:00,Hombres,GrandPrix,NaN,2026-06-05 00:00:00,1509.0,19
24,49779,43419.0,10.0,Jairo Moreira,Uruguay,NaN,3:53.57,1.0,NaN,233.57,932.0,1.500 Metros Planos,2026-04-19,12:45:00,Hombres,GrandPrix,NaN,2026-06-05 00:00:00,1509.0,19
26,46672,7619.0,5.0,Cristofer Jarpa Gallegos,Atlético Tempo,NaN,3:54.25,1.0,NaN,234.25,924.0,1.500 Metros Planos,2026-03-07,21:00:00,Hombres,TodoCompetidor,NaN,2026-06-05 00:00:00,1510.0,19
28,47243,19075.0,5.0,Juan Pablo Gelmi Garrido,Universidad Católica,NaN,3:54.67,3.0,NaN,234.67,918.0,1.500 Metros Planos,2026-03-21,17:20:00,Hombres,"Adulto,U18,U20",NaN,2026-06-05 00:00:00,1556.0,19
29,47243,19412.0,6.0,Mauricio Andrés Valdivia Verdugo,Atlético Rengo,NaN,3:55.01,3.0,NaN,235.01,914.0,1.500 Metros Planos,2026-03-21,17:20:00,Hombres,"Adulto,U18,U20",NaN,2026-06-05 00:00:00,1556.0,19
31,47243,31652.0,7.0,Cristobal Sierralta Henríquez,Atlético Valparaiso,NaN,3:55.95,3.0,NaN,235.95,903.0,1.500 Metros Planos,2026-03-21,17:20:00,Hombres,"Adulto,U18,U20",NaN,2026-06-05 00:00:00,1556.0,19
35,48256,8049.0,8.0,Leslie Rigoberto Encina Quintana,Ejercito de Chile,NaN,3:57.01,2.0,NaN,237.01,890.0,1.500 Metros Planos,2026-04-11,12:20:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1503.0,19
37,46650,26966.0,1.0,Cristobal Fernando Israel Pailla,Atlético Tempo,NaN,3:57.65,2.0,NaN,237.65,882.0,1.500 Metros Planos,2026-02-28,17:15:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1501.0,19
40,46672,3532.0,7.0,Dante Didier Carvajal Duarte,Atlético Francés,NaN,3:59.89,1.0,NaN,239.89,856.0,1.500 Metros Planos,2026-03-07,21:00:00,Hombres,TodoCompetidor,NaN,2026-06-05 00:00:00,1510.0,19
41,47243,24627.0,10.0,Ignacio Alexander Carrizo Godoy,"Atlético Fe, Esperanza y Amor",NaN,4:00.05,1.0,NaN,240.05,854.0,1.500 Metros Planos,2026-03-21,17:20:00,Hombres,"Adulto,U18,U20",NaN,2026-06-05 00:00:00,1556.0,19
43,46672,27511.0,8.0,Javier Alexander Candia Silva,Atlético Tempo,NaN,4:00.64,1.0,NaN,240.64,847.0,1.500 Metros Planos,2026-03-07,21:00:00,Hombres,TodoCompetidor,NaN,2026-06-05 00:00:00,1510.0,19
44,46672,28434.0,9.0,Jareb Juseph Figueroa Tarzon,Atlético Phoenix,NaN,4:00.81,1.0,NaN,240.81,845.0,1.500 Metros Planos,2026-03-07,21:00:00,Hombres,TodoCompetidor,NaN,2026-06-05 00:00:00,1510.0,19
45,48256,11281.0,10.0,Daniel Neemias Flandez Villanueva,Atlético Valle Mariquina,NaN,4:00.87,2.0,NaN,240.87,844.0,1.500 Metros Planos,2026-04-11,12:20:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1503.0,19
51,51519,8275.0,1.0,Omar Ceballo Betanzo,Carabineros de Chile,NaN,4:02.06,2.0,NaN,242.06,830.0,1.500 Metros Planos,2026-06-14,13:30:00,Hombres,"Adulto,U18,U20",NaN,2026-06-15 23:28:27,1690.0,19
54,47243,26947.0,12.0,Mario Hernán Rivas Vallejos,Atlético Phoenix,NaN,4:02.72,2.0,NaN,242.72,823.0,1.500 Metros Planos,2026-03-21,17:20:00,Hombres,"Adulto,U18,U20",NaN,2026-06-05 00:00:00,1556.0,19
55,51519,7737.0,2.0,Luis Zagal Monsalve,Carabineros de Chile,NaN,4:02.77,2.0,NaN,242.77,822.0,1.500 Metros Planos,2026-06-14,13:30:00,Hombres,"Adulto,U18,U20",NaN,2026-06-15 23:28:27,1690.0,19
56,50308,9309.0,1.0,Diego Alejandro Alvarez Tabilo,Atlético Valle del Huasco,NaN,4:03.54,2.0,NaN,243.54,813.0,1.500 Metros Planos,2026-05-16,17:40:00,Hombres,U20,NaN,2026-06-05 00:00:00,1504.0,19
59,51519,6703.0,3.0,Gerson Zapata Benavente,Carabineros de Chile,NaN,4:04.22,2.0,NaN,244.22,805.0,1.500 Metros Planos,2026-06-14,13:30:00,Hombres,"Adulto,U18,U20",NaN,2026-06-15 23:28:27,1690.0,19
60,51481,1803.0,2.0,Jeremy Alexander Olmedo Araya,Ejercito de Chile,NaN,4:04.31,1.0,NaN,244.31,804.0,1.500 Metros Planos,2026-06-06,18:25:00,Hombres,"Adulto,U18,U20",NaN,2026-06-15 23:27:47,1689.0,19
61,51519,39573.0,4.0,Luciano Alexis Saez Vega,Atlético Francés,NaN,4:04.86,1.0,NaN,244.86,798.0,1.500 Metros Planos,2026-06-14,13:30:00,Hombres,"Adulto,U18,U20",NaN,2026-06-15 23:28:27,1690.0,19
62,50403,27224.0,NaN,Cristian Ariel Espinoza Retamal,Ejercito de Chile,NaN,4:05.07,1.0,NaN,245.07,796.0,1.500 Metros Planos,2026-05-30,12:15:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1559.0,19
63,47243,23461.0,13.0,Fernando Alfredo Henríquez Nuñez,Cultura Física - Viña del Mar,NaN,4:05.29,1.0,NaN,245.29,793.0,1.500 Metros Planos,2026-03-21,17:20:00,Hombres,"Adulto,U18,U20",NaN,2026-06-05 00:00:00,1556.0,19
64,50403,24192.0,NaN,Yanclaudio Daniel Vera Céspedes,Círculo Atlético San Antonio,NaN,4:05.48,2.0,NaN,245.48,791.0,1.500 Metros Planos,2026-05-30,12:15:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1559.0,19
65,48256,6030.0,12.0,Nicolas Marcelo Opazo Arancibia,Atlético La Pintana,NaN,4:05.61,2.0,NaN,245.61,790.0,1.500 Metros Planos,2026-04-11,12:20:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1503.0,19
68,51519,8271.0,5.0,Michael Pinela Pinela,Carabineros de Chile,NaN,4:05.99,2.0,NaN,245.99,785.0,1.500 Metros Planos,2026-06-14,13:30:00,Hombres,"Adulto,U18,U20",NaN,2026-06-15 23:28:27,1690.0,19
69,50859,9523.0,1.0,Fernando Fritz Berríos,Universidad de Chile,NaN,4:06.06,1.0,NaN,246.06,784.0,1.500 Metros Planos,2026-06-07,12:30:00,Hombres,Adulto,NaN,2026-06-15 23:19:12,1677.0,19
72,46672,65098.0,11.0,Diego Andres Sanhueza Incontrolable,Atlético Nahuén,NaN,4:06.56,1.0,NaN,246.56,779.0,1.500 Metros Planos,2026-03-07,21:00:00,Hombres,TodoCompetidor,NaN,2026-06-05 00:00:00,1510.0,19
73,49599,14930.0,1.0,Vicente Miguel Sarabia Fernández,Atlético Fluvial,NaN,4:06.59,1.0,NaN,246.59,778.0,1.500 Metros Planos,2026-04-18,11:50:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1658.0,19
74,50859,27548.0,2.0,José Raimundo Dossow Jara,Pontificia Universidad Católica de Chile,NaN,4:06.83,1.0,NaN,246.83,776.0,1.500 Metros Planos,2026-06-07,12:30:00,Hombres,Adulto,NaN,2026-06-15 23:19:12,1677.0,19
75,49447,24890.0,2.0,Julio Luis Gutierrez Contreras,Universidad del Bio Bio - Concepción,NaN,4:06.90,1.0,NaN,246.90,775.0,1.500 Metros Planos,2026-05-02,16:15:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1654.0,19
76,51350,51553.0,1.0,Lucas Martin Ramirez Sanchez,Atlético Maullín,NaN,4:07.01,1.0,NaN,247.01,774.0,1.500 Metros Planos,2026-06-06,16:15:00,Hombres,U18,NaN,2026-06-15 23:26:02,1685.0,19
80,50403,65236.0,NaN,Emiliano Javier Abarca Salinas,Ciudad del Trueno,NaN,4:08.08,1.0,NaN,248.08,762.0,1.500 Metros Planos,2026-05-30,12:15:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1559.0,19
81,51519,77276.0,6.0,Jose Andres San Juan Carruz,Carabineros de Chile,NaN,4:08.03,2.0,NaN,248.03,762.0,1.500 Metros Planos,2026-06-14,13:30:00,Hombres,"Adulto,U18,U20",NaN,2026-06-15 23:28:27,1690.0,19
85,51208,39344.0,2.0,Valentin Acuña Flores,Nicolás Carvajal - Talagante,NaN,4:08.53,1.0,NaN,248.53,757.0,1.500 Metros Planos,2026-06-12,16:15:00,Hombres,U20,NaN,2026-06-15 23:23:36,1624.0,19
87,50403,2638.0,NaN,Nicolas Jara Poblete,Atlético La Pintana,NaN,4:08.64,3.0,NaN,248.64,756.0,1.500 Metros Planos,2026-05-30,12:15:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1559.0,19
89,50007,39134.0,1.0,Mario Ernesto Chavez Yera,Atlético Los Ángeles,NaN,4:09.42,1.0,NaN,249.42,747.0,1.500 Metros Planos,2026-04-25,12:00:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1664.0,19
91,50308,27505.0,4.0,Vicente Agustin Cea Sepulveda,Atlético Nahuelbuta,NaN,4:09.52,2.0,NaN,249.52,746.0,1.500 Metros Planos,2026-05-16,17:40:00,Hombres,U20,NaN,2026-06-05 00:00:00,1504.0,19
92,47243,43474.0,15.0,Ignacio Sepúlveda Medina,DSC Diamantes de Coronel,NaN,4:09.80,2.0,NaN,249.80,743.0,1.500 Metros Planos,2026-03-21,17:20:00,Hombres,"Adulto,U18,U20",NaN,2026-06-05 00:00:00,1556.0,19
93,46672,14890.0,12.0,Nicolas Andres Gómez Zuñiga,Cultura Física - Viña del Mar,NaN,4:09.84,1.0,NaN,249.84,742.0,1.500 Metros Planos,2026-03-07,21:00:00,Hombres,TodoCompetidor,NaN,2026-06-05 00:00:00,1510.0,19
95,51519,25857.0,7.0,Juan Jose Aubele Leon,Universidad Católica,NaN,4:10.22,2.0,NaN,250.22,738.0,1.500 Metros Planos,2026-06-14,13:30:00,Hombres,"Adulto,U18,U20",NaN,2026-06-15 23:28:27,1690.0,19
96,51348,54979.0,1.0,Camilo Ignacio Miranda Alvarado,Atlético Maullín,NaN,4:10.30,1.0,NaN,250.30,737.0,1.500 Metros Planos,2026-06-06,16:15:00,Hombres,Adulto,NaN,2026-06-15 23:26:01,1685.0,19
97,47243,24194.0,16.0,Juan Carlos Garrido Ramirez,Círculo Atlético San Antonio,NaN,4:10.41,2.0,NaN,250.41,736.0,1.500 Metros Planos,2026-03-21,17:20:00,Hombres,"Adulto,U18,U20",NaN,2026-06-05 00:00:00,1556.0,19
98,46650,27519.0,2.0,Vicente Israel Pailla,Atlético Tempo,NaN,4:10.58,2.0,NaN,250.58,734.0,1.500 Metros Planos,2026-02-28,17:15:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1501.0,19
99,50305,42491.0,7.0,Agustin Pardo Soto,Atlético Tempo,NaN,4:10.57,1.0,NaN,250.57,734.0,1.500 Metros Planos,2026-05-16,17:10:00,Hombres,U23,NaN,2026-06-05 00:00:00,1504.0,19
100,51349,27514.0,1.0,Ignacio Alejandro Vidal Plaza,"Atlético Fe, Esperanza y Amor",NaN,4:10.68,1.0,NaN,250.68,733.0,1.500 Metros Planos,2026-06-06,16:15:00,Hombres,U20,NaN,2026-06-15 23:26:01,1685.0,19
101,49266,63671.0,2.0,Martin Nicolas Montiel Torres,Círculo Atlético San Antonio,NaN,4:10.77,1.0,NaN,250.77,732.0,1.500 Metros Planos,2026-04-18,09:00:00,Hombres,TodoCompetidor,NaN,2026-06-05 00:00:00,1546.0,19
102,50859,7390.0,3.0,Jose Manuel Silva Ojeda,Universidad Diego Portales,NaN,4:10.81,1.0,NaN,250.81,732.0,1.500 Metros Planos,2026-06-07,12:30:00,Hombres,Adulto,NaN,2026-06-15 23:19:12,1677.0,19
103,49447,22949.0,3.0,Rodemil Armando Ponce Aravena,Ejercito de Chile,NaN,4:11.00,1.0,NaN,251.00,730.0,1.500 Metros Planos,2026-05-02,16:15:00,Hombres,Adulto,NaN,2026-06-05 00:00:00,1654.0,19

## Extraer organizaciones y paises

In [ ]:
colegios = atletas["Colegio"].dropna().drop_duplicates()
colegios.index = np.arange(1, len(colegios) + 1)
colegios = pd.DataFrame(colegios)
colegios.to_csv('colegios.csv', index_label='id_colegio')

In [ ]:
clubes = atletas["Club"].dropna().drop_duplicates()
clubes.index = np.arange(1, len(clubes) + 1)
clubes = pd.DataFrame(clubes)
clubes.to_csv('clubes.csv', index_label='id_club')

In [ ]:
clubes_master = atletas["Club Master"].dropna().drop_duplicates()
clubes_master.index = np.arange(1, len(clubes_master) + 1)
clubes_master = pd.DataFrame(clubes_master)
clubes_master.to_csv('clubes_master.csv', index_label='id_club_master')

In [ ]:
paises = atletas["Pais"].dropna().drop_duplicates()
paises.index = np.arange(1, len(paises) + 1)
paises = pd.DataFrame(paises)
paises.to_csv('paises.csv', index_label='id_pais')